name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Configure git for HTTPS access
      run: |
        git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install frontend dependencies
      run: npm run frontend:install
      
    - name: Compile contracts
      run: npm run hardhat:compile
      
    - name: Build frontend
      run: npm run build
      
  #  - name: Run linting
  #    run: npm run lint
      
    - name: Run all Hardhat tests
      run: npm run hardhat:test
      env:
        # Use hardhat network for testing - no external RPC needed
        HARDHAT_NETWORK: hardhat
      
    - name: Generate test coverage report
      run: npm run hardhat:coverage
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      if: always()
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
